[CheetahGenerator]
    encoding = utf8
    search_list_extensions = user.xstats.ExtendedStatistics, user.inigo.InigoSearchList

    [[inigo-last-year]]
        template = inigo-last-year.json.tmpl
            
[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator
