[CheetahGenerator]
    encoding = utf8
    search_list_extensions = user.xstats.ExtendedStatistics, user.inigo.InigoSearchList

    [[inigo-dicts]]
        report_timing = @monthlyCreateIfMissing
        template = inigo-dicts.json.tmpl
            
    [[inigo-data]]
        template = inigo-data.json.tmpl

    [[inigo-yesterday]]
        report_timing = @dailyCreateIfMissing
        template = inigo-yesterday.json.tmpl
            
    [[inigo-last-month]]
        report_timing = @monthlyCreateIfMissing
        template = inigo-last-month.json.tmpl
            
    [[inigo-last-year]]
        report_timing = @yearlyCreateIfMissing
        template = inigo-last-year.json.tmpl
            
[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator
