[CheetahGenerator]
    encoding = utf8
    search_list_extensions = user.xstats.ExtendedStatistics, user.inigo-since.Since, user.peak_detector.PeakDetectorSearchList

    [[ToDate]]
        [[[inigo-txt]]]
            template = inigo-data.txt.tmpl
        [[[inigo-json]]]
            template = inigo-data.json.tmpl
            
[Generators]
    generator_list = weewx.cheetahgenerator.CheetahGenerator
